parameters:
#    boilerplate_architecture.example.class: Boilerplate\ArchitectureBundle\Example

services:
  boilerplate.architecture.response.provider.users:
    alias: boilerplate.architecture.response.provider.users.file
