parameters:
#    boilerplate_architecture.example.class: Boilerplate\ArchitectureBundle\Example

services:
#    boilerplate_architecture.example:
#        class: %boilerplate_architecture.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
